server:
  port: 9999
spring:
  application:
    name: OAuth
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://152.136.206.111:3306/glq?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  redis:
    database: 0
    host: 152.136.206.111
    port: 6379
    timeout: 10000ms
    password: gao123
#    lettuce:
#      pool:
#        # 连接池最大连接数（使用负值表示没有限制）
#        max-active: 200
#        # 连接池中的最大空闲连接
#        max-idle: 20
#        # 连接池中的最小空闲连接
#        min-idle: 10
#        # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms
mybatis:
  mapper-locations: classpath:mapper/*.xml
  # 开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true